const CATALOG = [
  {sku:"EKT-1001",name_ru:"Автоматический выключатель ВА47-29 1P 16А",name_kk:"ВА47-29 1P 16А автоматты ажыратқышы",name_en:"Circuit breaker VA47-29 1P 16A",category:"breakers",price:1450,stock:25,certificate:"EAC-RU.МЛ32.B.01234"},
  {sku:"EKT-1002",name_ru:"Автоматический выключатель ВА47-29 1P 25А",name_kk:"ВА47-29 1P 25А автоматты ажыратқышы",name_en:"Circuit breaker VA47-29 1P 25A",category:"breakers",price:1600,stock:0,certificate:"EAC-RU.МЛ32.B.01235"},
  {sku:"EKT-2001",name_ru:"Кабель ВВГнг-LS 3x2.5",name_kk:"ВВГнг-LS 3x2.5 кабелі",name_en:"Cable VVGng-LS 3x2.5",category:"cables",price:320,stock:500,certificate:"EAC-RU.МЛ32.B.02001"},
  {sku:"EKT-3001",name_ru:"Розетка с заземлением IP44",name_kk:"Жерге тұйықталған розетка IP44",name_en:"Grounded socket IP44",category:"sockets",price:850,stock:60,certificate:"EAC-RU.МЛ32.B.03001"}
];

const T = {
  ru:{top_status:"Онлайн · подбор оборудования",eyebrow:"УМНЫЙ ПОМОЩНИК EKT.KZ",hero_title:"Найдём нужное<br>для вашего проекта.",hero_copy:"Подскажем по наличию, цене и сертификатам электротехнической продукции.",feature1_title:"Быстрый поиск",feature1_copy:"По артикулу или названию",feature2_title:"Актуальные данные",feature2_copy:"Цены и остатки на складе",feature3_title:"Подтверждённое качество",feature3_copy:"Номер сертификата в карточке",footer_note:"Технологии, которым доверяют",assistant_name:"Ассистент ekt.kz",online:"На связи",today:"СЕГОДНЯ",secure:"Информация о товарах обновляется",confirm_prompt:"Добавить в корзину?",yes:"Да, добавить",no:"Отмена",try_search:"Попробуйте найти",placeholder:"Введите артикул или название товара...",input_label:"Артикул или название товара",send:"Отправить",disclaimer:"Ассистент помогает подобрать товары из каталога",footer_right:"Электротехника для профессионалов",greeting:"Здравствуйте! Я ассистент ekt.kz. Напишите артикул или название товара — проверю цену, наличие и сертификат.",not_found:"К сожалению, товар не найден. Проверьте артикул или попробуйте другое название.",out:"Этого товара сейчас нет на складе. Вот доступные товары из той же категории:",no_alternatives:"К сожалению, в этой категории сейчас нет аналогов.",ask:"Подтвердите добавление товара в корзину?",added:"Товар добавлен в корзину.",cancelled:"Хорошо, корзина не изменена.",price:"Цена",stock:"Остаток",certificate:"Сертификат",pieces:"шт.",cart:"Товаров в корзине:"},
  kk:{top_status:"Желіде · жабдық таңдау",eyebrow:"EKT.KZ АҚЫЛДЫ КӨМЕКШІСІ",hero_title:"Жобаңызға керегін<br>бірге табамыз.",hero_copy:"Электр тауарларының бағасы, қоймадағы қоры және сертификаттары туралы айтамыз.",feature1_title:"Жылдам іздеу",feature1_copy:"Артикулы немесе атауы бойынша",feature2_title:"Өзекті мәліметтер",feature2_copy:"Бағалар мен қоймадағы қалдық",feature3_title:"Сапасы расталған",feature3_copy:"Сертификат нөмірі карточкада",footer_note:"Сенімді технологиялар",assistant_name:"ekt.kz көмекшісі",online:"Желіде",today:"БҮГІН",secure:"Тауарлар туралы ақпарат жаңартылады",confirm_prompt:"Себетке қосу керек пе?",yes:"Иә, қосу",no:"Болдырмау",try_search:"Іздеп көріңіз",placeholder:"Артикул немесе тауар атауын жазыңыз...",input_label:"Артикул немесе тауар атауы",send:"Жіберу",disclaimer:"Көмекші каталогтан тауар таңдауға көмектеседі",footer_right:"Мамандарға арналған электр жабдықтары",greeting:"Сәлеметсіз бе! Мен ekt.kz көмекшісімін. Артикулды немесе тауар атауын жазыңыз — бағасын, қорын және сертификатын тексеремін.",not_found:"Өкінішке орай, тауар табылмады. Артикулды тексеріп, басқа атауды қолданып көріңіз.",out:"Бұл тауар қазір қоймада жоқ. Осы санаттағы қолжетімді тауарлар:",no_alternatives:"Өкінішке орай, осы санатта қазір аналог жоқ.",ask:"Тауарды себетке қосуды растайсыз ба?",added:"Тауар себетке қосылды.",cancelled:"Жарайды, себет өзгертілмеді.",price:"Бағасы",stock:"Қалдық",certificate:"Сертификат",pieces:"дана",cart:"Себеттегі тауарлар:"},
  en:{top_status:"Online · equipment finder",eyebrow:"EKT.KZ SMART ASSISTANT",hero_title:"Find what you need<br>for your next project.",hero_copy:"Check availability, pricing and certificates for electrical supplies.",feature1_title:"Fast product search",feature1_copy:"Search by SKU or product name",feature2_title:"Current stock data",feature2_copy:"Prices and warehouse availability",feature3_title:"Verified quality",feature3_copy:"Certificate number on every item",footer_note:"Technology you can trust",assistant_name:"ekt.kz Assistant",online:"Available now",today:"TODAY",secure:"Product information is kept up to date",confirm_prompt:"Add to cart?",yes:"Yes, add",no:"Cancel",try_search:"Try searching",placeholder:"Enter a SKU or product name...",input_label:"SKU or product name",send:"Send",disclaimer:"The assistant helps you find products in the catalog",footer_right:"Electrical supplies for professionals",greeting:"Hello! I'm the ekt.kz assistant. Enter a product SKU or name to check its price, availability and certificate.",not_found:"Sorry, no product found. Check the SKU or try another name.",out:"This item is currently out of stock. Here are available products in the same category:",no_alternatives:"Unfortunately, there are no alternatives in this category right now.",ask:"Confirm adding this item to your cart?",added:"Item added to your cart.",cancelled:"Okay, your cart was not changed.",price:"Price",stock:"In stock",certificate:"Certificate",pieces:"items",cart:"Items in cart:"}
};
let currentLang="ru", pending=null;
const messagesEl=document.getElementById("messages"),inputEl=document.getElementById("userInput"),quickActions=document.getElementById("quickActions");
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function addMessage(text,sender="bot",html=false){const node=document.createElement("div");node.className=`msg ${sender}`;if(html)node.innerHTML=text;else node.textContent=text;messagesEl.appendChild(node);messagesEl.scrollTop=messagesEl.scrollHeight;}
function setLang(lang){if(!T[lang])return;currentLang=lang;document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const value=T[lang][el.dataset.i18n];if(value!==undefined)el.innerHTML=value;});document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>el.placeholder=T[lang][el.dataset.i18nPlaceholder]);document.querySelectorAll(".language-switch button").forEach(button=>button.classList.toggle("active",button.dataset.lang===lang));}
function findProduct(query){const q=query.trim().toLocaleLowerCase();if(!q)return null;return CATALOG.find(p=>p.sku.toLocaleLowerCase()===q)||CATALOG.find(p=>[p.name_ru,p.name_kk,p.name_en].some(name=>name.toLocaleLowerCase().includes(q)))||null;}
function productCard(item){const name=item[`name_${currentLang}`]||item.name_ru;return `<strong>${escapeHtml(name)} · ${escapeHtml(item.sku)}</strong>\n${T[currentLang].price}: ${item.price.toLocaleString()} ₸\n${T[currentLang].stock}: ${item.stock} ${T[currentLang].pieces}\n${T[currentLang].certificate}: ${escapeHtml(item.certificate)}`;}
function handleUserMessage(query){pending=null;quickActions.hidden=true;const item=findProduct(query);if(!item){addMessage(T[currentLang].not_found);return;}if(item.stock===0){const alternatives=CATALOG.filter(p=>p.category===item.category&&p.sku!==item.sku&&p.stock>0).slice(0,3);if(!alternatives.length){addMessage(T[currentLang].no_alternatives);return;}addMessage(`${T[currentLang].out}\n\n${alternatives.map(productCard).join("\n\n")}`,"bot",true);return;}pending=item;addMessage(`${productCard(item)}\n\n${T[currentLang].ask}`,"bot",true);quickActions.hidden=false;}
function sendMessage(query=inputEl.value){const text=query.trim();if(!text)return;addMessage(text,"user");inputEl.value="";document.getElementById("suggestions").hidden=true;handleUserMessage(text);}
function confirmAction(confirmed){quickActions.hidden=true;if(!pending)return;addMessage(confirmed?T[currentLang].yes:T[currentLang].no,"user");if(confirmed){const cart=JSON.parse(sessionStorage.getItem("ekt-cart")||"[]");const existing=cart.find(p=>p.sku===pending.sku);if(existing)existing.qty+=1;else cart.push({sku:pending.sku,qty:1});sessionStorage.setItem("ekt-cart",JSON.stringify(cart));const total=cart.reduce((sum,p)=>sum+p.qty,0);addMessage(`${T[currentLang].added} ${T[currentLang].cart} ${total}.`);}else addMessage(T[currentLang].cancelled);pending=null;}
document.getElementById("chatForm").addEventListener("submit",event=>{event.preventDefault();sendMessage();});
document.querySelectorAll(".language-switch button").forEach(button=>button.addEventListener("click",()=>setLang(button.dataset.lang)));
document.querySelectorAll(".suggestions button").forEach(button=>button.addEventListener("click",()=>sendMessage(button.dataset.query)));
document.getElementById("yesBtn").addEventListener("click",()=>confirmAction(true));document.getElementById("noBtn").addEventListener("click",()=>confirmAction(false));
addMessage(T.ru.greeting);setLang("ru");
